version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: go.dockerfile
    ports:
      - 8080:8080
    links:
      - mysql
    tty: true
    volumes:
      - ./src:/go/src

  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: db.dockerfile
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: "${TZ}"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
